# Generated by Django 4.2.1 on 2023-09-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0006_alter_paramater_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramater',
            name='name',
            field=models.CharField(max_length=99999, unique=True),
        ),
    ]
