# Generated by Django 4.2.1 on 2023-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0006_alter_paramater_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='part',
            field=models.CharField(default='n', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentence',
            name='DE',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='EN',
            field=models.CharField(max_length=2000),
        ),
    ]
