# Generated by Django 4.2.1 on 2023-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0007_sentence_part_alter_sentence_de_alter_sentence_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='category',
            field=models.CharField(default='splitted', max_length=2000),
        ),
    ]
