# Generated by Django 4.2.1 on 2023-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0008_alter_paramater_name_alter_paramater_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='part',
            field=models.CharField(choices=[('vocabulary', 'vocabulary'), ('expression', 'expression')], default='jenny', max_length=200),
        ),
    ]
