# Generated by Django 4.2.1 on 2023-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0010_alter_sentence_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='EN',
            field=models.CharField(max_length=2000),
        ),
    ]
